version: '3.8'

services:
  this-to-that:
    build: .
    container_name: this_to_that
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: always
    security_opt:
      - no-new-privileges:true
